version: "3.9"
services:
  pgdb:
    image: "postgres:16"
    environment:
      POSTGRES_DATABASE: "falcon-manager"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpass"
      POSTGRES_ROOT_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
