name: falcon-manager
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
      - name: Build and push the images
        run: |
          for DockerfilePath in $(find . -name Dockerfile);
          do
            folder=${versionFilePath%"/Dockerfile"}
            IMAGE_NAME=${folder##*/}

            tmpName="image-$RANDOM"
            docker build $folder --file $folder/Dockerfile --tag $tmpName
            IMAGE_ID=falcon-manager/$IMAGE_NAME
            VERSION=${{ github.ref_name }}

            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION

            docker tag $tmpName $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
          done;
  redeploy:
    name: Redeploy - Webhook call
    runs-on: ubuntu-latest
    needs: [publish-docker-images]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'secret': '${{ secrets.DEPLOY_SECRET }}' }"
